Edit Haml
yasukoimaeda/chat-space pull request #3
Opened 2019-04-05 07:49 UTC by yasukoimaeda

2019-04-12 06:53 UTC, yasukoimaeda commented
#WHAT
指示書を見ながらstylesheetの作成。

#WHY
チャットスペースの画面実装のため。

READMEをマージする前にそのままのブランチで続きしてしまいました、、、。

2019-04-12 06:57 UTC, yasukoimaeda commented
# WHAT
指示書を見ながらstylesheetの作成。

# WHY
チャットスペースの画面実装のため。

READMEをマージする前にそのままのブランチで進めてしまいました、、、。

2019-04-12 07:03 UTC, katsu105 commented
gyazoなどで画像を送っていいただくことは可能でしょうか？

2019-04-12 07:48 UTC, katsu105 approved these changes

2019-04-14 03:39 UTC, yasukoimaeda commented
https://gyazo.com/c4ee3eba05e195bd70545e5ab13fcb51

もとの指示書の画像でよかったでしょうか？

2019-04-26 01:15 UTC, yasukoimaeda commented
だいぶ日が経ってしまったのですが返信なく、もう一度提出しました。

2019-04-26 02:18 UTC, miyagit commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ハッシュロケットをやめましょう。

2019-04-26 02:18 UTC, miyagit commented on app/views/layouts/mailer.html.haml
> +!!!
mailer系のファイルは削除しましょう。

2019-04-29 03:57 UTC, yasukoimaeda commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
訂正しました。

2019-04-29 03:58 UTC, yasukoimaeda commented on app/views/layouts/mailer.html.haml
> +!!!
削除しましたが削除しないといけないのは何故ですか？

2019-04-29 04:04 UTC, TOMARUMARU commented on app/views/layouts/mailer.html.haml
> +!!!
今回は使用しないので使わないファイルは削除した方がいいです

2019-04-29 04:19 UTC, yasukoimaeda commented on app/views/layouts/mailer.html.haml
> +!!!
承知しました。

2019-04-29 04:20 UTC, yasukoimaeda commented
ここまでで他訂正は大丈夫でしょうか？
マージしても問題ありませんか？

2019-04-29 04:26 UTC, TOMARUMARU reviewed
変更したらpushしてください

2019-04-29 04:31 UTC, yasukoimaeda commented
すみませんpushするの忘れてました。
pushしました。できてますか？

2019-04-29 04:39 UTC, ghost requested changes

2019-04-29 04:39 UTC, hiroki5123 commented on app/assets/stylesheets/modules/_chatscreen.scss
> +  width:calc(100% - 300px);
シンボルの後は半角スペースを開けるのが一般的です。
修正をお願い致します。

2019-04-29 04:39 UTC, hiroki5123 commented on app/assets/stylesheets/modules/_side-bar.scss
> +    padding: 0 20px
セミコロンが抜けています

2019-04-29 04:39 UTC, hiroki5123 commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
こちら修正されておりませんので修正をお願い致します

2019-04-29 04:39 UTC, hiroki5123 commented
画面のキャプチャをこちらに添付してください

2019-04-29 04:55 UTC, yasukoimaeda commented on app/assets/stylesheets/modules/_chatscreen.scss
> +  width:calc(100% - 300px);
修正しました。

2019-04-29 04:56 UTC, yasukoimaeda commented on app/assets/stylesheets/modules/_side-bar.scss
> +    padding: 0 20px
修正しました。

2019-04-29 06:40 UTC, yasukoimaeda commented
修正しましたが画面実装できません。。。

2019-04-29 06:42 UTC, TOMARUMARU approved these changes
LGTM

2019-04-29 06:54 UTC, merged